"""empty message

Revision ID: 79cdd9654154
Revises: 8b348cb5fa6c
Create Date: 2022-10-03 10:38:44.076507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79cdd9654154'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('colorPelo', sa.String(length=150), nullable=True),
    sa.Column('colorOjos', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('habitantes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajesFav',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('personajes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'personajes_id')
    )
    op.create_table('planetasFav',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('planetas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'planetas_id')
    )
    op.add_column('user', sa.Column('nickname', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'user', ['nickname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'nickname')
    op.drop_table('planetasFav')
    op.drop_table('personajesFav')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
